#!/usr/bin/perl
use warnings;
use strict;

print <<"";
<svg xmlns="http://www.w3.org/2000/svg">
<g>

my $l = 10;
my $s = 0.66;
my @a = (50, 10, -20, -40);
my $depth = 8;

sub group
{
	my $level = shift;
	my $alpha = sprintf "%0.3f", ($level * 1.0 / $depth);
	print qq{<line x1="0" y1="0" x2="0" y2="$l" stroke="black" stroke-opacity="$alpha" stroke-width="1"/>\n};
	return if $level == 0;

	for my $a (@a)
	{
		my $new_s = $s + (rand()-0.5) * 0.2;
		my $new_a = $a + (rand()-0.5) * 40;
		print qq{<g transform="translate(0 $l) scale($new_s) rotate($new_a)">\n};
		group($level-1);
		print "</g>\n";
	}
}


group($depth);

print <<"";
</g>
</svg>

__END__
